spring:
  application:
    name: Employee-Management-System

  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system
    username: root
    password: adminPass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect


